project_id = "qufalwhsuvvxcehvysdj"

[functions.send-email]
verify_jwt = true

[functions.send-ses-email]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = true

[functions.moderate-content]
verify_jwt = true
